services:
  falkordb:
    image: falkordb/falkordb:latest
    container_name: falkordb
    ports:
      - "6379:6379"  # Redis/FalkorDB default
      - "3000:3000"  # Optional for FalkorDB REST if exposed
    volumes:
      - falkor_data:/data
    networks:
      - graphrag_network

  falkordb-browser:
    image: falkordb/falkordb-browser:latest
    container_name: falkordb-browser
    ports:
      - "8092:8080"  # Browser UI exposed on localhost:8080
    environment:
      FALKORDB_BROWSER_REDIS_HOST: falkordb
      FALKORDB_BROWSER_REDIS_PORT: 6379
      FALKORDB_BROWSER_REDIS_USE_TLS: "false"
    depends_on:
      - falkordb
    networks:
      - graphrag_network

  postgres:
    image: pgvector/pgvector:0.6.2-pg16
    container_name: pgvector-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pgvector_data:/var/lib/postgresql/data
      - ./postgres/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - graphrag_network

networks:
  graphrag_network:
    driver: bridge

volumes:
  falkor_data:
  pgvector_data:
